local P=game:GetService("Players")
local U=game:GetService("UserInputService")
local R=game:GetService("RunService")
local LP=P.LocalPlayer
local CH=LP.Character or LP.CharacterAdded:Wait()
local T
for _,v in ipairs(LP:GetDescendants()) do if v.Name=="SyncAPI" then T=v.Parent break end end
if not T then for _,v in ipairs(game.ReplicatedStorage:GetDescendants()) do if v.Name=="SyncAPI" then T=v.Parent break end end end
assert(T,"F3X not found")
local RE=T.SyncAPI.ServerEndpoint
local function _(a) pcall(function() RE:InvokeServer(unpack(a)) end) end
function SetCollision(p,b)_({"SyncCollision",{{Part=p,CanCollide=b}}})end
function SetAnchor(b,p)_({"SyncAnchor",{{Part=p,Anchored=b}}})end
function CreatePart(c,p)_({"CreatePart","Normal",c,p})end
function CreateTruss(c,p)_({"CreatePart","Truss",c,p})end
function CreateWedge(c,p)_({"CreatePart","Wedge",c,p})end
function CreateCorner(c,p)_({"CreatePart","Corner",c,p})end
function CreateCylinder(c,p)_({"CreatePart","Cylinder",c,p})end
function CreateBall(c,p)_({"CreatePart","Ball",c,p})end
function CreateSeat(c,p)_({"CreatePart","Seat",c,p})end
function CreateVehicleSeat(c,p)_({"CreatePart","Vehicle Seat",c,p})end
function CreateSpawn(c,p)_({"CreatePart","Spawn",c,p})end
function DestroyPart(p)_({"Remove",{p}})end
function Remove(o)_({"Remove",o})end
function UndoRemove(o)_({"UndoRemove",o})end
function MovePart(p,c)_({"SyncMove",{{Part=p,CFrame=c}}})end
function SyncMove(c)_({"SyncMove",c})end
function MoveModel(m,p)_({"SyncMove",{{Model=m,Pivot=p}}})end
function Resize(p,s,c)_({"SyncResize",{{Part=p,CFrame=c,Size=s}}})end
function SyncResize(c)_({"SyncResize",c})end
function SyncRotate(c)_({"SyncRotate",c})end
function RotateModel(m,p)_({"SyncRotate",{{Model=m,Pivot=p}}})end
function AddMesh(p)_({"CreateMeshes",{{Part=p}}})end
function CreateMeshes(ps)local t={}for i,v in pairs(ps)do t[i]={Part=v}end _({"CreateMeshes",t})end
function SetMesh(p,id)_({"SyncMesh",{{Part=p,MeshId="rbxassetid://"..id}}})end
function SetTexture(p,id)_({"SyncMesh",{{Part=p,TextureId="rbxassetid://"..id}}})end
function MeshResize(p,s)_({"SyncMesh",{{Part=p,Scale=s}}})end
function SetMeshOffset(p,o)_({"SyncMesh",{{Part=p,Offset=o}}})end
function SetMeshType(p,m)_({"SyncMesh",{{Part=p,MeshType=m}}})end
function SetVertexColor(p,c)_({"SyncMesh",{{Part=p,VertexColor=c}}})end
function SyncMeshFull(p,mi,ti,mt,s,o,vc)_({"SyncMesh",{{Part=p,MeshId=mi and "rbxassetid://"..mi or nil,TextureId=ti and "rbxassetid://"..ti or nil,MeshType=mt,Scale=s,Offset=o,VertexColor=vc}}})end
function SetName(p,n)_({"SetName",{p},n})end
function SetNames(i,n)_({"SetName",i,n})end
function Weld(a,b,l)_({"CreateWelds",{a,b},l})end
function CreateWelds(p,t)_({"CreateWelds",p,t})end
function RemoveWelds(w)_({"RemoveWelds",w})end
function UndoRemovedWelds(w)_({"UndoRemovedWelds",w})end
function SetLocked(p,b)_({"SetLocked",{p},b})end
function SetLockedMulti(i,b)_({"SetLocked",i,b})end
function CreateSpotlight(p)_({"CreateLights",{{Part=p,LightType="SpotLight"}}})end
function CreatePointLight(p)_({"CreateLights",{{Part=p,LightType="PointLight"}}})end
function CreateSurfaceLight(p)_({"CreateLights",{{Part=p,LightType="SurfaceLight"}}})end
function SyncLighting(p,b)_({"SyncLighting",{{Part=p,LightType="SpotLight",Brightness=b}}})end
function SyncLightingFull(p,lt,b,r,c,s,f,a)_({"SyncLighting",{{Part=p,LightType=lt,Brightness=b,Range=r,Color=c,Shadows=s,Face=f,Angle=a}}})end
function Color(p,c)_({"SyncColor",{{Part=p,Color=c,UnionColoring=false}}})end
function SyncColor(p,c,u)_({"SyncColor",{{Part=p,Color=c,UnionColoring=u or false}}})end
function SyncSurface(p,s)_({"SyncSurface",{{Part=p,Surfaces=s}}})end
function SpawnDecal(p,f)_({"CreateTextures",{{Part=p,Face=f,TextureType="Decal"}}})end
function SpawnTexture(p,f)_({"CreateTextures",{{Part=p,Face=f,TextureType="Texture"}}})end
function AddDecal(p,a,f)_({"SyncTexture",{{Part=p,Face=f,TextureType="Decal",Texture="rbxassetid://"..a}}})end
function SetDecalTransparency(p,f,t)_({"SyncTexture",{{Part=p,Face=f,TextureType="Decal",Transparency=t}}})end
function SyncTextureProps(p,f,a,t,u,v)_({"SyncTexture",{{Part=p,Face=f,TextureType="Texture",Texture=a and "rbxassetid://"..a or nil,Transparency=t,StudsPerTileU=u,StudsPerTileV=v}}})end
function SetTrans(p,i)_({"SyncMaterial",{{Part=p,Transparency=i}}})end
function SetMaterial(p,m)_({"SyncMaterial",{{Part=p,Material=m}}})end
function SetReflectance(p,r)_({"SyncMaterial",{{Part=p,Reflectance=r}}})end
function SyncMaterial(p,m,t,r)_({"SyncMaterial",{{Part=p,Material=m,Transparency=t,Reflectance=r}}})end
function CreateSmoke(p)_({"CreateDecorations",{{Part=p,DecorationType="Smoke"}}})end
function CreateFire(p)_({"CreateDecorations",{{Part=p,DecorationType="Fire"}}})end
function CreateSparkles(p)_({"CreateDecorations",{{Part=p,DecorationType="Sparkles"}}})end
function SyncDecorate(p,d,pr)local c={Part=p,DecorationType=d}for k,v in pairs(pr)do c[k]=v end _({"SyncDecorate",{c}})end
function SyncSmoke(p,c,o,r,s)SyncDecorate(p,"Smoke",{Color=c,Opacity=o,RiseVelocity=r,Size=s})end
function SyncFire(p,c,sc,h,s)SyncDecorate(p,"Fire",{Color=c,SecondaryColor=sc,Heat=h,Size=s})end
function SyncSparkles(p,c)SyncDecorate(p,"Sparkles",{SparkleColor=c})end
function Clone(i,p)_({"Clone",i,p})end
function CreateGroup(g,p,i)_({"CreateGroup",g,p,i})end
function CreateModel(p,i)_({"CreateGroup","Model",p,i})end
function CreateFolder(p,i)_({"CreateGroup","Folder",p,i})end
function Ungroup(g)_({"Ungroup",g})end
function SetParent(i,p)_({"SetParent",i,p})end
function RecolorHandle(c)_({"RecolorHandle",c})end
function Export(p)_({"Export",p})end
function IsHttpEnabled()_({"IsHttpServiceEnabled"})end
function ExtractMesh(a)_({"ExtractMeshFromAsset",a})end
function ExtractDecalImage(a)_({"ExtractImageFromDecal",a})end
function SetMouseLock(e)_({"SetMouseLockEnabled",e})end
local K,Z,PA,N={}, {}, false,0
local BUILT,SPAWN={},{Normal=CreatePart,Wedge=CreateWedge,Corner=CreateCorner,Cylinder=CreateCylinder,Ball=CreateBall,Truss=CreateTruss,Seat=CreateSeat,VehicleSeat=CreateVehicleSeat,Spawn=CreateSpawn}
local ST={"tower","house","temple","fortress","skyscraper","shrine","arena","bunker","lighthouse","pyramid","obelisk","ruins","bridge","windmill","factory","dock","spaceship","castle","statue","treehouse","lab","market","train","robot","maze","garden"}
local MT={Enum.Material.Brick,Enum.Material.SmoothPlastic,Enum.Material.Wood,Enum.Material.Concrete,Enum.Material.Marble,Enum.Material.Cobblestone,Enum.Material.Metal,Enum.Material.Slate,Enum.Material.WoodPlanks,Enum.Material.Sandstone,Enum.Material.Neon,Enum.Material.Glass,Enum.Material.Granite,Enum.Material.DiamondPlate,Enum.Material.Ice}
local PN={{n="Speedy",mv=1.55,bd=.45,tc=.12,tf=.65,help=.3},{n="Sleepy",mv=.75,bd=1.35,tc=.45,tf=1.4,help=.15},{n="Worker",mv=1,bd=.8,tc=.22,tf=1,help=.26},{n="Turbo",mv=1.9,bd=.28,tc=.18,tf=.8,help=.35},{n="Careful",mv=.85,bd=1.1,tc=.2,tf=.9,help=.45},{n="Lazy",mv=.65,bd=1.6,tc=.55,tf=1.8,help=.08},{n="Builder",mv=1.15,bd=.65,tc=.16,tf=.8,help=.32},{n="Hyper",mv=1.75,bd=.38,tc=.32,tf=.7,help=.25}}
local function w(t)task.wait(t or 0)end
local function rr(a,b)return a+math.random()*(b-a)end
local function ri(a,b)return math.random(a,b)end
local function pk(t)return t[math.random(1,#t)]end
local function pal()local h=math.random()local s=rr(.35,.9)local v=rr(.5,1)return{main=Color3.fromHSV(h,s,v),accent=Color3.fromHSV((h+.08)%1,s*.8,v*.92),dark=Color3.fromHSV(h,s*.5,v*.32),light=Color3.fromHSV(h,s*.18,math.min(v*1.2,1)),roof=Color3.fromHSV((h+.5)%1,s*.6,v*.55),glass=Color3.fromHSV(.57,.25,.9),neon=Color3.fromHSV(math.random(),1,1),trim=Color3.fromHSV((h+.16)%1,s*.75,v*.82)}end
local function ground(p,ig)local rp=RaycastParams.new()rp.FilterType=Enum.RaycastFilterType.Exclude rp.FilterDescendantsInstances=ig or {}local h=workspace:Raycast(p+Vector3.new(0,220,0),Vector3.new(0,-520,0),rp)return h and h.Position.Y or p.Y-3 end
local function newest()local f for _,v in ipairs(workspace:GetChildren())do if v:IsA("BasePart") and not v.Name:find("UgandaKnuckle") then f=v end end return f end
local function lookcf(pos,target,off)local d=target-pos if d.Magnitude<.05 then d=Vector3.new(0,0,-1)end return CFrame.lookAt(pos,pos+d.Unit)*CFrame.Angles(0,math.pi+(off or 0),0)end
local function pset(p,c,s,co,m,t,r)local q=SPAWN[p or "Normal"] or CreatePart q(c,workspace)w(.11)local x=newest()if x then Resize(x,s or Vector3.new(4,4,4),c)w(.035)MovePart(x,c)w(.035)Color(x,co or Color3.fromRGB(163,162,165))w(.025)SyncMaterial(x,m or Enum.Material.SmoothPlastic,t or 0,r or 0)w(.025)SetAnchor(true,x)w(.015)SetCollision(x,true)w(.015)end return x end
local function make(pd,kd)local x=pset(pd.ptype,pd.cf,pd.size,pd.color,pd.mat,pd.trans,pd.refl)if x then if pd.name then SetName(x,pd.name)end if pd.mesh then AddMesh(x)w(.06)if pd.mesh.id then SetMesh(x,pd.mesh.id)end if pd.mesh.tex then SetTexture(x,pd.mesh.tex)end if pd.mesh.scale then MeshResize(x,pd.mesh.scale)end if pd.mesh.off then SetMeshOffset(x,pd.mesh.off)end end if pd.light then if pd.light.kind=="PointLight" then CreatePointLight(x)elseif pd.light.kind=="SurfaceLight" then CreateSurfaceLight(x)else CreateSpotlight(x)end w(.04)SyncLightingFull(x,pd.light.kind or "PointLight",pd.light.b or 2,pd.light.r or 16,pd.light.c or pd.color or Color3.new(1,1,1),true,Enum.NormalId.Top,90)end if pd.fire then CreateFire(x)w(.04)SyncFire(x,pd.color or Color3.new(1,0,0),Color3.new(1,1,0),pd.fire.h or 8,pd.fire.s or 5)end if pd.smoke then CreateSmoke(x)w(.04)SyncSmoke(x,pd.color or Color3.new(.4,.4,.4),.35,4,pd.smoke.s or 6)end if pd.spark then CreateSparkles(x)w(.04)SyncSparkles(x,pd.color or Color3.new(1,1,1))end if pd.tex then SpawnTexture(x,pd.tex.face or Enum.NormalId.Top)w(.04)SyncTextureProps(x,pd.tex.face or Enum.NormalId.Top,pd.tex.id or "6372755229",pd.tex.tr or .35,pd.tex.u or 2,pd.tex.v or 2)end end w(rr(.04,.12)*(kd and kd.person.bd or 1))return x end
local function ideas(kd)local s=pk(ST)if kd.seen and kd.seen[s] then local wds={"weirdtower","blobhouse","randomthing","unknownart","chaosbuild","f3xdream","strangebox"}s=pk(wds)end kd.seen=kd.seen or {}kd.seen[s]=true return{style=s,scale=rr(.75,1.55),cx=ri(1,4),pal=pal(),mat=pk(MT)}end
local function gen(id,o)local a={}local p=id.pal local m=id.mat local sc=id.scale local cx=id.cx local s=id.style local function N(c,z,co,ma,t,r)table.insert(a,{ptype="Normal",cf=c,size=z*sc,color=co,mat=ma or m,trans=t or 0,refl=r or 0})end local function W(c,z,co,ma)table.insert(a,{ptype="Wedge",cf=c,size=z*sc,color=co,mat=ma or m})end local function C(c,z,co,ma)table.insert(a,{ptype="Cylinder",cf=c,size=z*sc,color=co,mat=ma or m})end local function B(c,z,co)table.insert(a,{ptype="Ball",cf=c,size=z*sc,color=co,mat=Enum.Material.Neon,spark=math.random()>.65})end local function Tt(c,z,co,ma)table.insert(a,{ptype="Truss",cf=c,size=z*sc,color=co,mat=ma or Enum.Material.Metal})end local function Cr(c,z,co,ma)table.insert(a,{ptype="Corner",cf=c,size=z*sc,color=co,mat=ma or m})end local function L(c,z,co,kind)table.insert(a,{ptype="Normal",cf=c,size=z*sc,color=co,mat=Enum.Material.Neon,light={kind=kind or "PointLight",b=3,r=22,c=co}})end
if s=="tower" then local Wd=ri(7,14)local H=ri(26,62)N(o*CFrame.new(0,1,0),Vector3.new(Wd+5,2,Wd+5),p.dark,Enum.Material.Concrete)N(o*CFrame.new(0,H/2+2,0),Vector3.new(Wd,H,Wd),p.main)for i=1,ri(3,7+cx)do local y=5+i*(H-9)/(7+cx)N(o*CFrame.new(-Wd/2-.1,y,0),Vector3.new(.5,ri(3,5),1.2),p.glass,Enum.Material.Glass,.25)N(o*CFrame.new(Wd/2+.1,y,0),Vector3.new(.5,ri(3,5),1.2),p.glass,Enum.Material.Glass,.25)end C(o*CFrame.new(0,H+9,0)*CFrame.Angles(0,0,math.pi/2),Vector3.new(.35,14,.35),p.dark,Enum.Material.Metal)L(o*CFrame.new(4,H+15,0),Vector3.new(7,3,.25),p.neon,"SurfaceLight")
elseif s=="house" then local Wd=ri(13,26)local D=ri(10,22)local H=ri(8,18)local RH=ri(4,9)N(o*CFrame.new(0,.5,0),Vector3.new(Wd+2,1,D+2),p.dark,Enum.Material.Concrete)N(o*CFrame.new(0,H/2+1,-D/2),Vector3.new(Wd,H,1),p.main)N(o*CFrame.new(0,H/2+1,D/2),Vector3.new(Wd,H,1),p.main)N(o*CFrame.new(-Wd/2,H/2+1,0),Vector3.new(1,H,D),p.main)N(o*CFrame.new(Wd/2,H/2+1,0),Vector3.new(1,H,D),p.main)N(o*CFrame.new(0,1,0),Vector3.new(Wd-.4,.4,D-.4),p.light,Enum.Material.WoodPlanks)N(o*CFrame.new(0,3,-D/2-.1),Vector3.new(4,6,.5),p.dark,Enum.Material.Wood)for i=1,ri(2,5)do N(o*CFrame.new(-Wd/2+Wd/(6)*i,H/2+1,-D/2-.1),Vector3.new(2.4,3,.3),p.glass,Enum.Material.Glass,.35)end W(o*CFrame.new(0,H+1+RH/2,0),Vector3.new(Wd+2,RH,D/2+1),p.roof,Enum.Material.Slate)W(o*CFrame.new(0,H+1+RH/2,0)*CFrame.Angles(0,math.pi,0),Vector3.new(Wd+2,RH,D/2+1),p.roof,Enum.Material.Slate)
elseif s=="temple" then local Wd=ri(24,42)local D=ri(16,30)local H=ri(10,18)for i=0,3 do N(o*CFrame.new(0,i*1.1+.55,0),Vector3.new(Wd+8-i*2,1.1,D+8-i*2),p.light,Enum.Material.Marble)end for i=0,ri(5,9)do local x=-Wd/2+2+i*(Wd-4)/8 C(o*CFrame.new(x,H/2+5,-D/2+1)*CFrame.Angles(0,0,math.pi/2),Vector3.new(H,2.4,2.4),p.main,Enum.Material.Marble)C(o*CFrame.new(x,H/2+5,D/2-1)*CFrame.Angles(0,0,math.pi/2),Vector3.new(H,2.4,2.4),p.main,Enum.Material.Marble)end N(o*CFrame.new(0,H+6,0),Vector3.new(Wd+4,2,D+4),p.accent,Enum.Material.Marble)W(o*CFrame.new(0,H+10,-D/2),Vector3.new(Wd+3,7,D/2),p.light,Enum.Material.Marble)W(o*CFrame.new(0,H+10,D/2)*CFrame.Angles(0,math.pi,0),Vector3.new(Wd+3,7,D/2),p.light,Enum.Material.Marble)L(o*CFrame.new(0,7,0),Vector3.new(4,4,4),p.neon)
elseif s=="fortress" or s=="castle" then local FW=ri(32,58)local FD=ri(32,58)local H=ri(12,24)N(o*CFrame.new(0,.5,0),Vector3.new(FW,1,FD),p.dark,Enum.Material.Concrete)for _,q in ipairs({{0,-FD/2,FW,1.5},{0,FD/2,FW,1.5},{-FW/2,0,1.5,FD},{FW/2,0,1.5,FD}})do N(o*CFrame.new(q[1],H/2+1,q[2]),Vector3.new(q[3],H,q[4]),p.main)end for _,c in ipairs({Vector3.new(-FW/2,0,-FD/2),Vector3.new(FW/2,0,-FD/2),Vector3.new(-FW/2,0,FD/2),Vector3.new(FW/2,0,FD/2)})do N(o*CFrame.new(c.X,H/2+8,c.Z),Vector3.new(10,H+14,10),p.accent)Cr(o*CFrame.new(c.X,H+17,c.Z),Vector3.new(12,7,12),p.roof,Enum.Material.Slate)end N(o*CFrame.new(0,5,-FD/2-.2),Vector3.new(8,10,1),p.dark,Enum.Material.Wood)
elseif s=="skyscraper" then local Wd=ri(11,23)local D=ri(11,23)local H=ri(45,95)N(o*CFrame.new(0,H/2,0),Vector3.new(Wd,H,D),p.main,Enum.Material.SmoothPlastic,.05,.05)for f=0,ri(7,14)do N(o*CFrame.new(0,f*H/12+.5,0),Vector3.new(Wd+.7,.45,D+.7),p.accent,Enum.Material.Metal)end for r=1,7 do for c=1,4 do N(o*CFrame.new(-Wd/2+c*Wd/5,r*H/8,-D/2-.15),Vector3.new(Wd/6,H/12,.3),p.glass,Enum.Material.Glass,.32)end end L(o*CFrame.new(0,H+17,0),Vector3.new(2,2,2),p.neon)
elseif s=="shrine" or s=="garden" then local rad=ri(12,22)N(o*CFrame.new(0,.5,0),Vector3.new(rad*2+8,1,rad*2+8),Color3.fromRGB(80,120,60),Enum.Material.Grass)for i=0,ri(8,15)do local aa=i/12*math.pi*2 N(o*CFrame.new(math.cos(aa)*rad,ri(6,12)/2+1,math.sin(aa)*rad),Vector3.new(2,ri(6,12),2),p.main,Enum.Material.Cobblestone)end L(o*CFrame.new(0,5.5,0),Vector3.new(4,4,4),p.neon)Tt(o*CFrame.new(0,6,-rad-4),Vector3.new(10,10,2),p.accent,Enum.Material.Wood)
elseif s=="arena" then local rad=ri(18,32)local H=ri(10,19)C(o*CFrame.new(0,.5,0)*CFrame.Angles(0,0,math.pi/2),Vector3.new(1,rad*2,rad*2),p.dark,Enum.Material.Concrete)C(o*CFrame.new(0,H/2,0)*CFrame.Angles(0,0,math.pi/2),Vector3.new(H,(rad+5)*2,(rad+5)*2),p.main)C(o*CFrame.new(0,H/2+1,0)*CFrame.Angles(0,0,math.pi/2),Vector3.new(H+2,rad*2-4,rad*2-4),p.accent)for i=0,15 do local aa=i/16*math.pi*2 Tt(o*CFrame.new(math.cos(aa)*(rad+3),H/2+1,math.sin(aa)*(rad+3))*CFrame.Angles(0,aa,0),Vector3.new(2,H+2,2),p.light,Enum.Material.Metal)end
elseif s=="bunker" or s=="lab" then local Wd=ri(18,34)local D=ri(14,26)local H=ri(6,12)N(o*CFrame.new(0,H/2,0),Vector3.new(Wd,H,D),p.dark,Enum.Material.Concrete)N(o*CFrame.new(0,H+1,0),Vector3.new(Wd+3,2,D+3),p.main,Enum.Material.Concrete)N(o*CFrame.new(0,3,-D/2-.2),Vector3.new(5,6,.5),p.trim,Enum.Material.Metal)L(o*CFrame.new(0,H+3,0),Vector3.new(3,3,3),p.neon,"SpotLight")for i=1,5 do N(o*CFrame.new(-Wd/2+i*Wd/6,H/2,-D/2-.2),Vector3.new(1.5,3,.4),p.accent,Enum.Material.Metal)end
elseif s=="lighthouse" then local rad=ri(4,8)local H=ri(32,62)C(o*CFrame.new(0,1,0)*CFrame.Angles(0,0,math.pi/2),Vector3.new(2,(rad+3)*2,(rad+3)*2),p.dark,Enum.Material.Concrete)C(o*CFrame.new(0,H/2+2,0)*CFrame.Angles(0,0,math.pi/2),Vector3.new(H,rad*2,rad*2),p.main)for i=0,6 do C(o*CFrame.new(0,4+i*(H-4)/7,0)*CFrame.Angles(0,0,math.pi/2),Vector3.new(2,(rad+.1)*2,(rad+.1)*2),i%2==0 and p.accent or p.light)end L(o*CFrame.new(0,H+7,0),Vector3.new(rad+2,rad+2,rad+2),p.neon,"PointLight")
elseif s=="pyramid" then local base=ri(22,44)local lay=ri(5,9)for i=0,lay-1 do local side=base*(1-i/lay)N(o*CFrame.new(0,i*(base/lay/2)+1,0),Vector3.new(side,base/lay*1.4,side),Color3.fromHSV(.08,.6-i*.04,.85-i*.03),Enum.Material.Sandstone)end L(o*CFrame.new(0,lay*(base/lay/2)+4,0),Vector3.new(3,3,3),p.neon)
elseif s=="obelisk" or s=="statue" then local Wd=ri(5,9)local H=ri(24,54)N(o*CFrame.new(0,.5,0),Vector3.new(Wd+6,1,Wd+6),p.dark,Enum.Material.Marble)N(o*CFrame.new(0,H/2,0),Vector3.new(Wd,H,Wd),p.main,Enum.Material.Marble)for _,r in ipairs({0,math.pi,math.pi/2,-math.pi/2})do W(o*CFrame.new(0,H+3,0)*CFrame.Angles(0,r,0),Vector3.new(Wd,6,Wd/2),p.accent,Enum.Material.Marble)end B(o*CFrame.new(0,H+8,0),Vector3.new(3,3,3),p.neon)
elseif s=="ruins" then local Wd=ri(16,32)local D=ri(12,26)N(o*CFrame.new(0,.5,0),Vector3.new(Wd+5,1,D+5),Color3.fromRGB(80,105,55),Enum.Material.Grass)for i=0,ri(4,8)do local aa=i/6*math.pi*2 N(o*CFrame.new(math.cos(aa)*Wd/2,ri(4,15)/2,math.sin(aa)*D/2)*CFrame.Angles(0,aa,0),Vector3.new(rr(1.5,3),rr(6,17),rr(4,8)),p.main,Enum.Material.Cobblestone)end for i=1,ri(6,14)do N(o*CFrame.new(rr(-Wd/2,Wd/2),rr(.6,2),rr(-D/2,D/2))*CFrame.Angles(rr(0,.6),rr(0,6.28),rr(0,.6)),Vector3.new(rr(1,4),rr(.5,2),rr(1,4)),p.dark,Enum.Material.Cobblestone)end
elseif s=="bridge" or s=="dock" then local Lg=ri(35,70)local Wd=ri(8,14)for i=-Lg/2,Lg/2,6 do N(o*CFrame.new(i,.7,0),Vector3.new(5,1.4,Wd),p.dark,Enum.Material.WoodPlanks)Tt(o*CFrame.new(i,5,-Wd/2),Vector3.new(2,10,2),p.accent,Enum.Material.Metal)Tt(o*CFrame.new(i,5,Wd/2),Vector3.new(2,10,2),p.accent,Enum.Material.Metal)end for z=-1,1,2 do N(o*CFrame.new(0,8,z*Wd/2),Vector3.new(Lg,1,1),p.trim,Enum.Material.Metal)end
elseif s=="windmill" then N(o*CFrame.new(0,8,0),Vector3.new(10,16,10),p.main,Enum.Material.Wood)W(o*CFrame.new(0,19,0),Vector3.new(12,8,6),p.roof,Enum.Material.Slate)W(o*CFrame.new(0,19,0)*CFrame.Angles(0,math.pi,0),Vector3.new(12,8,6),p.roof,Enum.Material.Slate)L(o*CFrame.new(0,18,-6),Vector3.new(2,2,2),p.neon)for _,r in ipairs({0,math.pi/2,math.pi,math.pi*1.5})do N(o*CFrame.new(0,18,-7)*CFrame.Angles(0,0,r),Vector3.new(2,16,.5),p.light,Enum.Material.WoodPlanks)end
elseif s=="factory" then local Wd=ri(28,48)local D=ri(18,32)local H=ri(12,22)N(o*CFrame.new(0,H/2,0),Vector3.new(Wd,H,D),p.main,Enum.Material.Metal,.04,.05)for i=1,3 do C(o*CFrame.new(-Wd/2+i*Wd/4,H+9,0)*CFrame.Angles(0,0,math.pi/2),Vector3.new(18,4,4),p.dark,Enum.Material.Metal)table.insert(a,{ptype="Normal",cf=o*CFrame.new(-Wd/2+i*Wd/4,H+20,0),size=Vector3.new(5,5,5)*sc,color=Color3.fromRGB(70,70,70),mat=Enum.Material.SmoothPlastic,trans=.45,smoke={s=10}})end
elseif s=="spaceship" then C(o*CFrame.new(0,8,0)*CFrame.Angles(0,0,math.pi/2),Vector3.new(36,8,8),p.main,Enum.Material.Metal,.05,.15)W(o*CFrame.new(20,8,0)*CFrame.Angles(0,0,-math.pi/2),Vector3.new(10,8,8),p.accent,Enum.Material.Metal)for z=-1,1,2 do W(o*CFrame.new(-3,5,z*8)*CFrame.Angles(0,z*.8,0),Vector3.new(18,3,10),p.trim,Enum.Material.Metal)end L(o*CFrame.new(-20,8,0),Vector3.new(4,4,4),Color3.fromRGB(0,180,255))
elseif s=="treehouse" then C(o*CFrame.new(0,10,0)*CFrame.Angles(0,0,math.pi/2),Vector3.new(20,5,5),Color3.fromRGB(90,55,25),Enum.Material.Wood)for i=1,12 do B(o*CFrame.new(rr(-12,12),rr(18,28),rr(-12,12)),Vector3.new(ri(6,10),ri(6,10),ri(6,10)),Color3.fromRGB(40,130,40))end N(o*CFrame.new(0,23,0),Vector3.new(16,10,16),p.main,Enum.Material.WoodPlanks)W(o*CFrame.new(0,31,0),Vector3.new(18,7,9),p.roof,Enum.Material.Wood)W(o*CFrame.new(0,31,0)*CFrame.Angles(0,math.pi,0),Vector3.new(18,7,9),p.roof,Enum.Material.Wood)
elseif s=="market" then N(o*CFrame.new(0,.5,0),Vector3.new(42,1,24),p.light,Enum.Material.Sandstone)for i=-2,2 do N(o*CFrame.new(i*8,3,0),Vector3.new(6,5,8),p.main,Enum.Material.Wood)W(o*CFrame.new(i*8,8,0),Vector3.new(8,4,5),p.neon,Enum.Material.Fabric)W(o*CFrame.new(i*8,8,0)*CFrame.Angles(0,math.pi,0),Vector3.new(8,4,5),p.accent,Enum.Material.Fabric)end
elseif s=="train" then for i=0,4 do N(o*CFrame.new(i*13,5,0),Vector3.new(11,8,8),i==0 and p.accent or p.main,Enum.Material.Metal)for x=-1,1,2 do for z=-1,1,2 do C(o*CFrame.new(i*13+x*4,1.7,z*4)*CFrame.Angles(0,0,math.pi/2),Vector3.new(1,3,3),p.dark,Enum.Material.Metal)end end end C(o*CFrame.new(-8,10,0)*CFrame.Angles(0,0,math.pi/2),Vector3.new(9,3,3),p.dark,Enum.Material.Metal,0,0)table.insert(a,{ptype="Normal",cf=o*CFrame.new(-8,16,0),size=Vector3.new(5,5,5)*sc,color=Color3.fromRGB(80,80,80),mat=Enum.Material.SmoothPlastic,trans=.5,smoke={s=8}})
elseif s=="robot" then N(o*CFrame.new(0,18,0),Vector3.new(12,18,7),p.main,Enum.Material.Metal)N(o*CFrame.new(0,32,0),Vector3.new(10,10,10),p.accent,Enum.Material.Metal)L(o*CFrame.new(-2,33,-5.1),Vector3.new(1.5,1.5,.5),Color3.fromRGB(255,0,0))L(o*CFrame.new(2,33,-5.1),Vector3.new(1.5,1.5,.5),Color3.fromRGB(255,0,0))for x=-1,1,2 do N(o*CFrame.new(x*10,18,0),Vector3.new(5,17,5),p.trim,Enum.Material.Metal)N(o*CFrame.new(x*4,4,0),Vector3.new(5,16,5),p.dark,Enum.Material.Metal)end
elseif s=="maze" then N(o*CFrame.new(0,.5,0),Vector3.new(42,1,42),p.dark,Enum.Material.Concrete)for i=1,24 do local x=ri(-18,18)local z=ri(-18,18)local rot=math.random()>.5 and 0 or math.pi/2 N(o*CFrame.new(x,4,z)*CFrame.Angles(0,rot,0),Vector3.new(ri(6,14),8,1.5),p.main,Enum.Material.Brick)end L(o*CFrame.new(0,6,0),Vector3.new(3,3,3),p.neon)
else local n=ri(12,28)for i=1,n do local q=Vector3.new(rr(-18,18),rr(2,20),rr(-18,18))local typ=pk({"Normal","Wedge","Corner","Cylinder","Ball","Truss","Seat","Spawn"})table.insert(a,{ptype=typ,cf=o*CFrame.new(q)*CFrame.Angles(rr(0,6.28),rr(0,6.28),rr(0,6.28)),size=Vector3.new(rr(2,10),rr(2,14),rr(2,10))*sc,color=Color3.fromHSV(math.random(),rr(.4,1),rr(.55,1)),mat=pk(MT),trans=rr(0,.25),refl=rr(0,.15),light=math.random()>.86 and {kind="PointLight",b=2,r=12,c=p.neon} or nil,spark=math.random()>.8})end end return a end
local function radius(pl)local r=18 for _,pd in ipairs(pl)do local v=pd.cf.Position r=math.max(r,(Vector3.new(v.X,0,v.Z)-Vector3.new(pl[1].cf.Position.X,0,pl[1].cf.Position.Z)).Magnitude+12)end return math.min(r,85)end
local function blocked(pos,rad)for _,z in ipairs(Z)do if z.on and (Vector3.new(pos.X,0,pos.Z)-Vector3.new(z.pos.X,0,z.pos.Z)).Magnitude<rad+z.rad then return z end end return nil end
local function site(kd,id,base)local tries=0 while tries<25 do tries+=1 local p=base+Vector3.new(rr(-75,75),0,rr(-75,75))local g=ground(p,{kd.body})local cf=CFrame.new(p.X,g,p.Z)local l=gen(id,cf)local r=radius(l)local b=blocked(cf.Position,r)if not b then local z={on=true,pos=cf.Position,rad=r,owner=kd,style=id.style,state="claimed",parts=l,helpers={}}table.insert(Z,z)return z else kd.status="knows blocked" print("[Knuckle #"..kd.id.."] cannot build "..id.style.." there because #"..(b.owner and b.owner.id or 0).." is already building/built")w(rr(.2,.7))end end return nil end
local function face(a,b,t)local A=a.body and a.body.Parent local B=b.body and b.body.Parent if A and B then local p=a.body.Position local q=b.body.Position a.body.CFrame=lookcf(p,q) b.body.CFrame=lookcf(q,p)end w(t or 1)end
local function walk(kd,tp,sp,done)task.spawn(function()if not(kd.active and kd.body and kd.body.Parent)then return end kd.status="moving"local gy=ground(tp,{kd.body})local dst=Vector3.new(tp.X,gy+2.1,tp.Z)local src=kd.body.Position local d=(dst-src).Magnitude local st=.025/(kd.person.mv or 1)if sp=="slow"then st=st*1.65 end local steps=math.max(14,math.floor(d*(3.2/(kd.person.mv or 1))))for i=1,steps do if not(kd.active and kd.body and kd.body.Parent)then return end while PA do w(.2)end local a=i/steps local t=a<.5 and 2*a*a or 1-(-2*a+2)^2/2 local pos=src:Lerp(dst,t)+Vector3.new(0,math.abs(math.sin(a*math.pi*8))*((sp=="slow")and .05 or .12),0)kd.body.CFrame=lookcf(pos,dst)w(st)end kd.body.CFrame=lookcf(dst,dst+(dst-src))if done then task.spawn(done)end end)end
local function drop(kd,done)task.spawn(function()local src=kd.body.Position local gy=ground(src,{kd.body})local dst=Vector3.new(src.X,gy+2.1,src.Z)for i=1,math.max(8,math.floor(math.abs(src.Y-dst.Y)*2))do if not(kd.body and kd.body.Parent)then return end local a=i/math.max(8,math.floor(math.abs(src.Y-dst.Y)*2))kd.body.CFrame=CFrame.new(src:Lerp(dst,1-(1-a)^3))w(.02)end kd.body.CFrame=CFrame.new(dst)if done then task.spawn(done)end end)end
local function tired(kd,done)task.spawn(function()kd.status="tired"local tm=rr(6,17)*(kd.person.tf or 1)local e=0 while e<tm do if not(kd.active and kd.body and kd.body.Parent)then return end while PA do w(.25)end local p=kd.body.Position kd.body.CFrame=CFrame.new(p)*CFrame.Angles(0,math.sin(tick()*.5)*.25,0)e+=.07 if math.random()<.012 then local d=false walk(kd,p+Vector3.new(rr(-8,8),0,rr(-8,8)),"slow",function()d=true end)local t=0 while not d and t<5 do w(.05)t+=.05 end e+=t else w(.07)end end kd.status="idle"if done then task.spawn(done)end end)end
local function knuckle(pos)N+=1 local id=N CreatePart(CFrame.new(pos),workspace)w(.18)local b=newest()if not b then return nil,id end Resize(b,Vector3.new(4,4,4),CFrame.new(pos))w(.05)MovePart(b,CFrame.new(pos))w(.05)SetTrans(b,0)w(.04)Color(b,Color3.fromRGB(200,50,30))w(.04)SetMaterial(b,Enum.Material.SmoothPlastic)w(.04)SetAnchor(true,b)w(.04)SetCollision(b,false)w(.04)AddMesh(b)w(.1)SetMesh(b,"3088025494")w(.06)SetTexture(b,"3088025925")w(.06)MeshResize(b,Vector3.new(.3,.3,.3))w(.06)SetMeshOffset(b,Vector3.new(0,6,0))w(.06)SetName(b,"UgandaKnuckle_"..id)return b,id end
local function helperFor(kd)local picks={}for _,z in ipairs(Z)do if z.on and z.state=="building" and z.owner~=kd and z.owner and z.owner.active and not z.helpers[kd] then table.insert(picks,z)end end return #picks>0 and pk(picks) or nil end
local function work(kd,z,from,to,helping)local parts=z.parts kd.status=helping and "helping" or "building" kd.building=z.style kd.totalParts=#parts for i=from,to do local pd=parts[i]if not pd then break end if not(kd.active and kd.body and kd.body.Parent)then return end while PA do w(.2)end local bp=pd.cf.Position local nx=bp.X+rr(-4,4)local nz=bp.Z+rr(-4,4)local ny=ground(Vector3.new(nx,0,nz),{kd.body})+2.1 kd.body.CFrame=lookcf(Vector3.new(nx,ny,nz),bp)make(pd,kd)kd.builtCount+=1 end end
local function ai(kd)task.spawn(function()while kd.active and kd.body and kd.body.Parent do while PA do w(.4)end if math.random()<kd.person.tc then local d=false tired(kd,function()d=true end)while not d do w(.1)end end kd.status="thinking"w(rr(.35,1.7))if not(kd.active and kd.body and kd.body.Parent)then return end local hz if math.random()<kd.person.help then hz=helperFor(kd)end if hz then hz.helpers[kd]=true kd.status="understands help"kd.building="helping "..hz.style local hpos=hz.owner.body.Position local d=false walk(kd,hpos+Vector3.new(rr(3,7),0,rr(3,7)),"normal",function()d=true end)while not d do w(.05)end face(kd,hz.owner,rr(.8,2.1))local mid=math.floor(#hz.parts*.55)work(kd,hz,mid,#hz.parts,true)kd.status="finished help"w(rr(.7,2))else local id=ideas(kd)local z=site(kd,id,kd.body.Position)if z then kd.claim=z kd.building=id.style kd.totalParts=#z.parts kd.builtCount=0 local g=ground(z.pos,{kd.body})local ar=false walk(kd,Vector3.new(z.pos.X+rr(6,10),g,z.pos.Z+rr(-5,5)),"normal",function()ar=true end)while not ar do w(.05)end z.state="building"work(kd,z,1,#z.parts,false)z.state="built"table.insert(BUILT,z)local dd=false kd.status="finishing"drop(kd,function()dd=true end)while not dd do w(.05)end kd.status="finished"w(rr(1,3))end end kd.status="idle"w(rr(.4,1.4))end end)end
local function spawn()local hrp=CH and CH:FindFirstChild("HumanoidRootPart")local sp;if hrp then local p=hrp.Position+hrp.CFrame.LookVector*6 local g=ground(p,{CH})sp=Vector3.new(p.X,g+2.1,p.Z)else sp=Vector3.new(0,5,0)end local b,id=knuckle(sp)if not b then warn("spawn failed")return end local pr=pk(PN)local kd={id=id,body=b,status="idle",active=true,building="none",builtCount=0,totalParts=0,person=pr,seen={}}table.insert(K,kd)w(.2)ai(kd)print("[Knuckle #"..id.."] "..pr.n.." personality spawned")end
local function clear()for _,kd in ipairs(K)do kd.active=false if kd.body and kd.body.Parent then DestroyPart(kd.body)end end K={}Z={}BUILT={}N=0 print("[Uganda Knuckles] cleared")end
local function pause()PA=not PA print("[Uganda Knuckles] "..(PA and "paused" or "resumed"))end
local function status()print("=== KNUCKLES ===")for _,kd in ipairs(K)do if kd.body and kd.body.Parent then print("#"..kd.id.." "..kd.person.n.." | "..kd.status.." | "..kd.building.." | "..kd.builtCount.."/"..kd.totalParts)end end print("zones "..#Z)if #K==0 then print("none")end print("================")end
local function force()for _,kd in ipairs(K)do if kd.active and kd.body and kd.body.Parent then task.spawn(function()kd.active=false w(.05)kd.active=true kd.status="idle"ai(kd)end)end end print("[Uganda Knuckles] restarted")end
local function hud()local old=LP.PlayerGui:FindFirstChild("UKHUD")if old then old:Destroy()end local sg=Instance.new("ScreenGui")sg.Name="UKHUD"sg.ResetOnSpawn=false sg.Parent=LP.PlayerGui local f=Instance.new("Frame")f.Size=UDim2.new(0,188,0,132)f.Position=UDim2.new(1,-196,1,-140)f.BackgroundColor3=Color3.new(0,0,0)f.BackgroundTransparency=.5 f.BorderSizePixel=0 f.Parent=sg local rows={{"Uganda Knuckles Builder v6",true},{"Z spawn knuckle",false},{"X remove all",false},{"C pause / resume",false},{"V print status",false},{"B force new build",false},{"build claiming + helping",false}}for i,row in ipairs(rows)do local l=Instance.new("TextLabel")l.Size=UDim2.new(1,-10,0,16)l.Position=UDim2.new(0,6,0,2+(i-1)*18)l.BackgroundTransparency=1 l.Text=row[1]l.TextColor3=row[2]and Color3.new(1,1,1)or Color3.fromRGB(175,175,175)l.Font=row[2]and Enum.Font.GothamBold or Enum.Font.Gotham l.TextSize=row[2]and 12 or 11 l.TextXAlignment=Enum.TextXAlignment.Left l.Parent=f end end
hud()
U.InputBegan:Connect(function(i,g)if g then return end task.spawn(function()local k=i.KeyCode if k==Enum.KeyCode.Z then spawn()elseif k==Enum.KeyCode.X then clear()elseif k==Enum.KeyCode.C then pause()elseif k==Enum.KeyCode.V then status()elseif k==Enum.KeyCode.B then force()end end)end)
LP.CharacterAdded:Connect(function(c)task.spawn(function()CH=c w(1)hud()end)end)
task.spawn(function()w(.2)print("[Uganda Knuckles v6] ready")end)
