local uis=game:GetService("UserInputService")local plrs=game:GetService("Players")local plr=plrs.LocalPlayer local char=plr.Character or plr.CharacterAdded:Wait()local tool for _,v in plr:GetDescendants()do if v.Name=="SyncAPI"then tool=v.Parent end end for _,v in game.ReplicatedStorage:GetDescendants()do if v.Name=="SyncAPI"then tool=v.Parent end end local remote=tool.SyncAPI.ServerEndpoint local function g(a)remote:InvokeServer(unpack(a))end local function fire(a)task.spawn(function()pcall(g,a)end)end
local MESH_ID=110961984000546 local TEX_NORMAL=95260716122801 local TEX_ZOMBIE=18580150967 local TEX_FIRE=11273380307 local MESH_SCALE=Vector3.new(0.04,0.04,0.04)local MESH_OFFSET=Vector3.new(0,-2,0)
local modes={"Passive","Fast","Angry","Stand","Circle"}local types={"Normal","Zombie","Kamikaze","Fire"}local modeIdx=1 local typeIdx=1 local curMode=modes[1]local curType=types[1]local cats={}local dead={}local MAX_CATS=40 local prevMode=""
local gui=Instance.new("ScreenGui")gui.Name="CatPanel"gui.ResetOnSpawn=false gui.Parent=plr.PlayerGui
local fr=Instance.new("Frame")fr.Size=UDim2.new(0,200,0,155)fr.Position=UDim2.new(0,10,1,-165)fr.BackgroundColor3=Color3.fromRGB(20,20,20)fr.BorderSizePixel=1 fr.BorderColor3=Color3.fromRGB(55,55,55)fr.Parent=gui
local tt=Instance.new("TextLabel")tt.Size=UDim2.new(1,0,0,22)tt.BackgroundTransparency=1 tt.Text="lolcatty army"tt.TextColor3=Color3.fromRGB(200,200,200)tt.TextSize=13 tt.Font=Enum.Font.SourceSansBold tt.Parent=fr
local function mkl(y,txt)local l=Instance.new("TextLabel")l.Size=UDim2.new(1,-10,0,16)l.Position=UDim2.new(0,5,0,y)l.BackgroundTransparency=1 l.Text=txt l.TextColor3=Color3.fromRGB(150,150,150)l.TextSize=12 l.Font=Enum.Font.SourceSans l.TextXAlignment=Enum.TextXAlignment.Left l.Parent=fr return l end
mkl(24,"E - spawn cat")mkl(40,"R - switch mode")mkl(56,"T - switch type")
local mLbl=mkl(76,"mode: Passive")mLbl.TextColor3=Color3.fromRGB(100,180,100)mLbl.Font=Enum.Font.SourceSansBold
local tLbl=mkl(94,"type: Normal")tLbl.TextColor3=Color3.fromRGB(100,150,220)tLbl.Font=Enum.Font.SourceSansBold
local cLbl=mkl(112,"cats: 0")cLbl.TextColor3=Color3.fromRGB(120,120,120)
local function gety(px,pz)local rp=RaycastParams.new()rp.FilterType=Enum.RaycastFilterType.Exclude local fl={}if char then fl[1]=char end for _,c in ipairs(cats)do if c.part and c.part.Parent then fl[#fl+1]=c.part end end rp.FilterDescendantsInstances=fl local r=workspace:Raycast(Vector3.new(px,500,pz),Vector3.new(0,-1000,0),rp)return r and r.Position.Y or nil end
local function mpos(m)if not m or not m.Parent then return nil,nil end local r=m:FindFirstChild("HumanoidRootPart")or m:FindFirstChild("Torso")or m:FindFirstChild("UpperTorso")or m:FindFirstChild("Head")if r and r:IsA("BasePart")and r.Parent then return r.Position,r end for _,v in m:GetDescendants()do if v:IsA("BasePart")then return v.Position,v end end return nil,nil end
local function cantarget(m)if not m or not m.Parent then return false end if dead[m]then return false end if not m:FindFirstChildOfClass("Humanoid")then return false end return mpos(m)~=nil end
local function getTargets()local list={}char=plr.Character for _,obj in workspace:GetChildren()do if obj:IsA("Model")and obj~=char and cantarget(obj)then list[#list+1]=obj end end for _,p in ipairs(plrs:GetPlayers())do if p~=plr and p.Character and p.Character~=char and cantarget(p.Character)then local dup=false for _,x in ipairs(list)do if x==p.Character then dup=true break end end if not dup then list[#list+1]=p.Character end end end return list end
local function removeRandomPart(m)if not m or not m.Parent then return end local bp={}for _,v in m:GetDescendants()do if v:IsA("BasePart")and v.Parent and v.Name~="HumanoidRootPart"then bp[#bp+1]=v end end if #bp>0 then fire({[1]="Remove",[2]={bp[math.random(1,#bp)]}})end end
local function burnModel(m)if dead[m]then return end dead[m]=true task.spawn(function()local parts={}for _,v in m:GetDescendants()do if v:IsA("BasePart")and v.Parent then parts[#parts+1]=v end end if #parts>0 then local cb,mb={},{}for i,p in ipairs(parts)do cb[i]={["Part"]=p,["Color"]=Color3.fromRGB(30,10,0),["UnionColoring"]=false}mb[i]={["Part"]=p,["Material"]=Enum.Material.Neon,["Transparency"]=0,["Reflectance"]=0}end fire({[1]="SyncColor",[2]=cb})fire({[1]="SyncMaterial",[2]=mb})end end)task.spawn(function()for _,v in m:GetDescendants()do if v:IsA("BasePart")and v.Parent then task.spawn(function()pcall(g,{[1]="CreateDecorations",[2]={{["Part"]=v,["DecorationType"]="Fire"}}})task.wait(0.1)fire({[1]="SyncDecorate",[2]={{["Part"]=v,["DecorationType"]="Fire",["Color"]=Color3.fromRGB(255,100,0),["SecondaryColor"]=Color3.fromRGB(255,200,0),["Heat"]=15,["Size"]=8}}})end)break end end end)task.spawn(function()local rm={}for _,v in m:GetChildren()do if v:IsA("Accessory")or v:IsA("Hat")then for _,c in v:GetDescendants()do if c:IsA("BasePart")then rm[#rm+1]=c end end end end if #rm>0 then fire({[1]="Remove",[2]=rm})end end)task.spawn(function()task.wait(4+math.random()*3)local head=m:FindFirstChild("Head")if head and head:IsA("BasePart")then fire({[1]="Remove",[2]={head}})end end)end
local function infectModel(m)if dead[m]then return end dead[m]=true task.spawn(function()local parts={}for _,v in m:GetDescendants()do if v:IsA("BasePart")and v.Parent then parts[#parts+1]=v end end if #parts>0 then local cb={}for i,p in ipairs(parts)do cb[i]={["Part"]=p,["Color"]=Color3.fromRGB(0,255,0),["UnionColoring"]=false}end fire({[1]="SyncColor",[2]=cb})end end)task.spawn(function()local rm={}for _,v in m:GetChildren()do if v:IsA("Accessory")or v:IsA("Hat")then for _,c in v:GetDescendants()do if c:IsA("BasePart")then rm[#rm+1]=c end end end end if #rm>0 then fire({[1]="Remove",[2]=rm})end end)task.spawn(function()task.wait(3+math.random()*2)local head=m:FindFirstChild("Head")if head and head:IsA("BasePart")then fire({[1]="Remove",[2]={head}})end local ep=mpos(m)if ep then task.spawn(function()spawnCat(ep+Vector3.new(math.random(-4,4),0,math.random(-4,4)),"Zombie")end)end end)end
local function killModel(m)if dead[m]then return end dead[m]=true task.spawn(function()local parts={}for _,v in m:GetDescendants()do if v:IsA("BasePart")and v.Parent then parts[#parts+1]=v end end if #parts>0 then local cb,mb={},{}for i,p in ipairs(parts)do cb[i]={["Part"]=p,["Color"]=Color3.fromRGB(35,35,35),["UnionColoring"]=false}mb[i]={["Part"]=p,["Material"]=Enum.Material.SmoothPlastic,["Transparency"]=0,["Reflectance"]=0}end fire({[1]="SyncColor",[2]=cb})fire({[1]="SyncMaterial",[2]=mb})end end)task.spawn(function()local rm={}for _,v in m:GetChildren()do if v:IsA("Accessory")or v:IsA("Hat")then for _,c in v:GetDescendants()do if c:IsA("BasePart")then rm[#rm+1]=c end end end end if #rm>0 then fire({[1]="Remove",[2]=rm})end end)task.spawn(function()task.wait(0.2)local head=m:FindFirstChild("Head")if head and head:IsA("BasePart")then fire({[1]="Remove",[2]={head}})return end local root=m:FindFirstChild("HumanoidRootPart")or m:FindFirstChild("Torso")if root and root:IsA("BasePart")then fire({[1]="Remove",[2]={root}})end end)end
function spawnCat(position,catType)if #cats>=MAX_CATS then return end local ct=catType or curType local gy2=gety(position.X,position.Z)local sy=gy2 and(gy2+2)or(position.Y+2)local cf=CFrame.new(position.X,sy,position.Z)
	pcall(g,{[1]="CreatePart",[2]="Normal",[3]=cf,[4]=workspace})
	task.wait(0.35)
	local part=nil for _,v in workspace:GetChildren()do if v:IsA("Part")and v.Name=="Part"and(v.Position-cf.Position).Magnitude<15 then part=v end end if not part then return end
	fire({[1]="SetName",[2]={part},[3]="LolCat"})
	fire({[1]="SyncAnchor",[2]={{["Part"]=part,["Anchored"]=true}}})
	fire({[1]="SyncCollision",[2]={{["Part"]=part,["CanCollide"]=false}}})
	fire({[1]="SyncMaterial",[2]={{["Part"]=part,["Transparency"]=0,["Material"]=Enum.Material.SmoothPlastic,["Reflectance"]=0}}})
	fire({[1]="SyncResize",[2]={{["Part"]=part,["CFrame"]=cf,["Size"]=Vector3.new(1,1,1)}}})
	task.wait(0.2)
	pcall(g,{[1]="CreateMeshes",[2]={{["Part"]=part}}})
	task.wait(0.2)
	local texId=TEX_NORMAL if ct=="Zombie"then texId=TEX_ZOMBIE elseif ct=="Fire"then texId=TEX_FIRE end
	pcall(g,{[1]="SyncMesh",[2]={{["Part"]=part,["MeshId"]="rbxassetid://"..MESH_ID,["Scale"]=MESH_SCALE,["Offset"]=MESH_OFFSET}}})
	task.wait(0.15)
	pcall(g,{[1]="SyncMesh",[2]={{["Part"]=part,["TextureId"]="rbxassetid://"..texId}}})
	task.wait(0.1)
	local cat={part=part,type=ct,x=cf.Position.X,z=cf.Position.Z,y=sy,baseY=sy,gx=cf.Position.X,gz=cf.Position.Z,wa=math.random()*math.pi*2,wdx=math.cos(math.random()*6.28),wdz=math.sin(math.random()*6.28),wtx=0,wtz=0,wct=tick()+math.random()+0.5,fa=math.random()*math.pi*2,birth=tick(),lastBite=0,bomb=nil,bombBirth=nil,alive=true,jumpY=0,jumpVel=0,jumping=false,nextJump=tick()+math.random()*3+1,tiltX=0,tiltZ=0,hasAngryLight=false}
	cat.wtx=cat.wdx cat.wtz=cat.wdz
	if ct=="Zombie"then task.spawn(function()task.wait(0.15)pcall(g,{[1]="CreateLights",[2]={{["Part"]=part,["LightType"]="PointLight"}}})task.wait(0.1)fire({[1]="SyncLighting",[2]={{["Part"]=part,["LightType"]="PointLight",["Brightness"]=20,["Range"]=8,["Color"]=Color3.fromRGB(0,255,0),["Shadows"]=true}}})end)end
	if ct=="Fire"then task.spawn(function()task.wait(0.15)pcall(g,{[1]="CreateDecorations",[2]={{["Part"]=part,["DecorationType"]="Fire"}}})task.wait(0.1)fire({[1]="SyncDecorate",[2]={{["Part"]=part,["DecorationType"]="Fire",["Color"]=Color3.fromRGB(255,80,0),["SecondaryColor"]=Color3.fromRGB(255,200,0),["Heat"]=25,["Size"]=15}}})task.wait(0.1)pcall(g,{[1]="CreateLights",[2]={{["Part"]=part,["LightType"]="PointLight"}}})task.wait(0.1)fire({[1]="SyncLighting",[2]={{["Part"]=part,["LightType"]="PointLight",["Brightness"]=15,["Range"]=12,["Color"]=Color3.fromRGB(255,120,0),["Shadows"]=true}}})end)end
	if ct=="Kamikaze"then task.spawn(function()task.wait(0.3)local bombCF=CFrame.new(part.Position+Vector3.new(0,1.5,0))pcall(g,{[1]="CreatePart",[2]="Ball",[3]=bombCF,[4]=workspace})task.wait(0.3)local bomb=nil for _,v in workspace:GetChildren()do if v:IsA("Part")and v.Shape==Enum.PartType.Ball and v.Name=="Part"and(v.Position-bombCF.Position).Magnitude<10 then bomb=v end end if bomb then fire({[1]="SetName",[2]={bomb},[3]="CatBomb"})fire({[1]="SyncResize",[2]={{["Part"]=bomb,["CFrame"]=bomb.CFrame,["Size"]=Vector3.new(1.2,1.2,1.2)}}})fire({[1]="SyncMaterial",[2]={{["Part"]=bomb,["Material"]=Enum.Material.Neon,["Transparency"]=0,["Reflectance"]=0}}})fire({[1]="SyncColor",[2]={{["Part"]=bomb,["Color"]=Color3.fromRGB(255,255,255),["UnionColoring"]=false}}})fire({[1]="SyncAnchor",[2]={{["Part"]=bomb,["Anchored"]=true}}})fire({[1]="SyncCollision",[2]={{["Part"]=bomb,["CanCollide"]=false}}})cat.bomb=bomb cat.bombBirth=tick()end end)end
	cats[#cats+1]=cat cLbl.Text="cats: "..#cats
	task.spawn(function()local c=cat local DT=0.03 while c.alive and c.part and c.part.Parent do local now=tick()char=plr.Character local mode=curMode local spd=mode=="Fast"and 42 or(mode=="Angry"and 35 or(c.type=="Zombie"and 18 or 26))local lerpA=mode=="Fast"and 0.18 or 0.12 local biteRange=6
			if mode=="Angry"and not c.hasAngryLight and c.type~="Zombie"and c.type~="Fire"then c.hasAngryLight=true task.spawn(function()pcall(g,{[1]="CreateLights",[2]={{["Part"]=c.part,["LightType"]="PointLight"}}})task.wait(0.1)fire({[1]="SyncLighting",[2]={{["Part"]=c.part,["LightType"]="PointLight",["Brightness"]=20,["Range"]=8,["Color"]=Color3.fromRGB(255,0,0),["Shadows"]=true}}})end)end
			if mode~="Angry"and c.hasAngryLight then c.hasAngryLight=false task.spawn(function()fire({[1]="SyncLighting",[2]={{["Part"]=c.part,["LightType"]="PointLight",["Brightness"]=0,["Range"]=0,["Color"]=Color3.fromRGB(0,0,0),["Shadows"]=false}}})end)end
			if now>=c.nextJump and not c.jumping and mode~="Stand"then c.jumping=true c.jumpVel=math.random(18,30)c.nextJump=now+math.random()*4+1.5 end
			if c.jumping then c.jumpY=c.jumpY+c.jumpVel*DT c.jumpVel=c.jumpVel-80*DT if c.jumpY<=0 then c.jumpY=0 c.jumpVel=0 c.jumping=false end end
			if mode=="Stand"then c.gx=c.x c.gz=c.z
			elseif mode=="Circle"then if char then local hrp2=char:FindFirstChild("HumanoidRootPart")if hrp2 then local idx=0 for i,cc in ipairs(cats)do if cc==c then idx=i break end end local total=math.max(#cats,1)local angle=(idx/total)*math.pi*2+now*0.5 local radius=7+total*0.4 c.gx=hrp2.Position.X+math.cos(angle)*radius c.gz=hrp2.Position.Z+math.sin(angle)*radius c.fa=math.atan2(math.sin(angle),math.cos(angle))+math.pi local cgy=gety(c.gx,c.gz)if cgy and cgy>-50 then c.baseY=c.baseY+(cgy+2-c.baseY)*0.12 end end end task.spawn(function()local tgts=getTargets()for _,m in ipairs(tgts)do local ep=mpos(m)if ep then local dd=math.sqrt((ep.X-c.x)^2+(ep.Z-c.z)^2)if dd<biteRange and now-c.lastBite>0.8 then c.lastBite=now if c.type=="Zombie"then task.spawn(infectModel,m)elseif c.type=="Fire"then task.spawn(burnModel,m)else task.spawn(removeRandomPart,m)end end end end end)
			elseif mode=="Passive"then if char then local hrp2=char:FindFirstChild("HumanoidRootPart")if hrp2 then local dx=hrp2.Position.X-c.x local dz=hrp2.Position.Z-c.z local dist=math.sqrt(dx*dx+dz*dz)if dist>4 then local inv=1/math.max(dist,0.01)c.gx=c.x+dx*inv*spd*DT c.gz=c.z+dz*inv*spd*DT c.fa=math.atan2(dz,dx)end end end task.spawn(function()local tgts=getTargets()for _,m in ipairs(tgts)do local ep=mpos(m)if ep then local dd=math.sqrt((ep.X-c.x)^2+(ep.Z-c.z)^2)if dd<biteRange and now-c.lastBite>0.8 and math.random()<0.4 then c.lastBite=now if c.type=="Zombie"then task.spawn(infectModel,m)elseif c.type=="Fire"then task.spawn(burnModel,m)else task.spawn(removeRandomPart,m)end end end end end)
			else
				local closest,closestDist=nil,math.huge local tgts=getTargets()for _,m in ipairs(tgts)do local ep=mpos(m)if ep then local dd=math.sqrt((ep.X-c.x)^2+(ep.Z-c.z)^2)if dd<closestDist and dd<60 then closest=m closestDist=dd end end end
				if closest and(mode=="Angry"or c.type=="Zombie"or c.type=="Fire")then local ep=mpos(closest)if ep then local dx=ep.X-c.x local dz=ep.Z-c.z local dist=math.sqrt(dx*dx+dz*dz)if dist>0.5 then local inv=1/dist c.gx=c.x+dx*inv*spd*DT c.gz=c.z+dz*inv*spd*DT c.fa=math.atan2(dz,dx)end if dist<biteRange and now-c.lastBite>0.6 then c.lastBite=now if c.type=="Zombie"then task.spawn(infectModel,closest)elseif c.type=="Fire"then task.spawn(burnModel,closest)elseif mode=="Angry"and math.random()<0.7 then task.spawn(killModel,closest)else task.spawn(removeRandomPart,closest)end end end
				else
					if now>=c.wct then c.wa=c.wa+(math.random()-0.5)*math.pi*0.9 c.wtx=math.cos(c.wa)c.wtz=math.sin(c.wa)c.wct=now+math.random()*1.5+0.5 end c.wdx=c.wdx+(c.wtx-c.wdx)*0.07 c.wdz=c.wdz+(c.wtz-c.wdz)*0.07 local wm=math.sqrt(c.wdx^2+c.wdz^2)if wm>0.01 then c.wdx=c.wdx/wm c.wdz=c.wdz/wm end c.gx=c.x+c.wdx*spd*DT c.gz=c.z+c.wdz*spd*DT c.fa=math.atan2(c.wdz,c.wdx)end end
			local ngy=gety(c.gx,c.gz)if ngy and ngy>-50 then c.baseY=c.baseY+(ngy+2-c.baseY)*0.12 elseif not ngy then else c.wa=c.wa+math.pi c.wdx=math.cos(c.wa)c.wdz=math.sin(c.wa)c.wtx=c.wdx c.wtz=c.wdz c.gx=c.x c.gz=c.z end
			local prevX,prevZ=c.x,c.z c.x=c.x+(c.gx-c.x)*lerpA c.z=c.z+(c.gz-c.z)*lerpA local velX=(c.x-prevX)/DT local velZ=(c.z-prevZ)/DT c.tiltX=c.tiltX+(math.clamp(velZ*0.008,-0.2,0.2)-c.tiltX)*0.12 c.tiltZ=c.tiltZ+(math.clamp(-velX*0.008,-0.2,0.2)-c.tiltZ)*0.12
			c.y=c.baseY+c.jumpY
			if c.bomb and c.bomb.Parent then task.spawn(function()fire({[1]="SyncMove",[2]={{["Part"]=c.bomb,["CFrame"]=CFrame.new(c.x,c.y+1.5,c.z)}}})end)local bt=now-(c.bombBirth or now)if math.sin(bt/(math.max(0.5-bt*0.03,0.05))*math.pi)>0 then task.spawn(function()fire({[1]="SyncColor",[2]={{["Part"]=c.bomb,["Color"]=Color3.fromRGB(255,30,30),["UnionColoring"]=false}}})end)else task.spawn(function()fire({[1]="SyncColor",[2]={{["Part"]=c.bomb,["Color"]=Color3.fromRGB(255,255,255),["UnionColoring"]=false}}})end)end
				if bt>6+math.random()*3 then local bx,bz=c.x,c.z task.spawn(function()fire({[1]="Remove",[2]={c.bomb}})end)task.spawn(function()fire({[1]="Remove",[2]={c.part}})end)c.bomb=nil c.alive=false task.spawn(function()local tgts=getTargets()for _,m in ipairs(tgts)do local ep=mpos(m)if ep then if math.sqrt((ep.X-bx)^2+(ep.Z-bz)^2)<15 then task.spawn(killModel,m)end end end end)for i=#cats,1,-1 do if cats[i]==c then table.remove(cats,i)end end cLbl.Text="cats: "..#cats break end end
			local bob=math.sin((now-c.birth)*4)*0.15+math.sin((now-c.birth)*7)*0.05
			task.spawn(function()fire({[1]="SyncMove",[2]={{["Part"]=c.part,["CFrame"]=CFrame.new(c.x,c.y+bob,c.z)*CFrame.Angles(c.tiltX,-c.fa-math.pi/2,c.tiltZ)}}})end)
			task.wait(DT)end
		for i=#cats,1,-1 do if cats[i]==c then table.remove(cats,i)end end cLbl.Text="cats: "..#cats end)end
uis.InputBegan:Connect(function(input,gpe)if gpe then return end if input.KeyCode==Enum.KeyCode.E then char=plr.Character or plr.CharacterAdded:Wait()local hrp2=char:FindFirstChild("HumanoidRootPart")if hrp2 then task.spawn(function()spawnCat(hrp2.Position+Vector3.new(math.random(-6,6),0,math.random(-6,6)),curType)end)end end if input.KeyCode==Enum.KeyCode.R then prevMode=curMode modeIdx=modeIdx%#modes+1 curMode=modes[modeIdx]mLbl.Text="mode: "..curMode if curMode=="Angry"then mLbl.TextColor3=Color3.fromRGB(220,60,60)elseif curMode=="Fast"then mLbl.TextColor3=Color3.fromRGB(220,180,50)elseif curMode=="Circle"then mLbl.TextColor3=Color3.fromRGB(100,150,220)elseif curMode=="Stand"then mLbl.TextColor3=Color3.fromRGB(160,160,160)else mLbl.TextColor3=Color3.fromRGB(100,180,100)end end if input.KeyCode==Enum.KeyCode.T then typeIdx=typeIdx%#types+1 curType=types[typeIdx]tLbl.Text="type: "..curType if curType=="Zombie"then tLbl.TextColor3=Color3.fromRGB(0,200,0)elseif curType=="Kamikaze"then tLbl.TextColor3=Color3.fromRGB(255,120,0)elseif curType=="Fire"then tLbl.TextColor3=Color3.fromRGB(255,60,0)else tLbl.TextColor3=Color3.fromRGB(100,150,220)end end end)
