local a=game:GetService("ReplicatedStorage")local b=game.Players.LocalPlayer local c=b.Character or b.CharacterAdded:Wait()local d for i,v in b:GetDescendants()do if v.Name=="SyncAPI"then d=v.Parent end end for i,v in a:GetDescendants()do if v.Name=="SyncAPI"then d=v.Parent end end local e=d.SyncAPI.ServerEndpoint local function f(g)e:InvokeServer(unpack(g))end
task.spawn(function()pcall(function()local h=a:WaitForChild("HDAdminHDClient",10)if h then local i=h:WaitForChild("Signals",5)if i then local j=i:FindFirstChild("RequestCommandSilent")or i:FindFirstChild("RequestCommand")if j then j:InvokeServer(";titleo me renderyo")end end end end)end)
task.wait(2)c=b.Character or b.CharacterAdded:Wait()local k=c:WaitForChild("Head",5)if not k then return end if not k:FindFirstChildWhichIsA("BillboardGui")then task.wait(2)end
local l={}local m={[k]=true}for _,n in ipairs({"UpperTorso","LowerTorso","HumanoidRootPart","LeftUpperArm","LeftLowerArm","LeftHand","RightUpperArm","RightLowerArm","RightHand","LeftUpperLeg","LeftLowerLeg","LeftFoot","RightUpperLeg","RightLowerLeg","RightFoot","Torso","Left Arm","Right Arm","Left Leg","Right Leg"})do local o=c:FindFirstChild(n)if o and(o:IsA("BasePart")or o:IsA("MeshPart"))and not m[o]then m[o]=true l[#l+1]=o end end for _,v in c:GetDescendants()do if(v:IsA("BasePart")or v:IsA("MeshPart"))and not m[v]then m[v]=true l[#l+1]=v end end
local p=#l if p==0 then return end
local q={}for _,v in workspace:GetDescendants()do if v:IsA("BasePart")and v.Name=="Head"then q[v]=true end end
for i=1,p do task.spawn(function()pcall(function()f({[1]="Clone",[2]={k},[3]=workspace})end)end)end
task.wait(1.5)
local r={}for _,v in workspace:GetChildren()do if v:IsA("BasePart")and v.Name=="Head"and not q[v]and v~=k then r[#r+1]=v end end if #r<p then for _,v in workspace:GetDescendants()do if v:IsA("BasePart")and v.Name=="Head"and not q[v]and v~=k then local s=false for _,h in ipairs(r)do if h==v then s=true break end end if not s then r[#r+1]=v end end end end
local t=math.min(#r,p)if t==0 then return end
local u={}for i=1,t do u[i]=r[i]end pcall(f,{[1]="SetName",[2]=u,[3]="renderyos"})
task.wait(0.1)
local v={}for i=1,t do for _,w in r[i]:GetDescendants()do if w:IsA("Decal")or w:IsA("Texture")then v[#v+1]=w end end end if #v>0 then task.spawn(function()pcall(f,{[1]="Remove",[2]=v})end)end
task.wait(0.1)
local x,y,z={},{},{}for i=1,t do x[i]={["Part"]=r[i],["Transparency"]=1}y[i]={["Part"]=r[i],["CanCollide"]=false}z[i]={["Part"]=r[i],["Anchored"]=true}end task.spawn(function()pcall(f,{[1]="SyncMaterial",[2]=x})end)task.spawn(function()pcall(f,{[1]="SyncCollision",[2]=y})end)task.spawn(function()pcall(f,{[1]="SyncAnchor",[2]=z})end)
task.wait(0.15)
local A={}for i=1,t do A[i]={["Part"]=r[i],["CFrame"]=l[i].CFrame}end task.spawn(function()pcall(f,{[1]="SyncMove",[2]=A})end)
task.wait(0.15)
for i=1,t do task.spawn(function()pcall(function()f({[1]="CreateWelds",[2]={r[i],l[i]},[3]=l[i]})end)end)end
task.wait(0.15)
local B={}for i=1,t do B[i]={["Part"]=r[i],["Anchored"]=false}end task.spawn(function()pcall(f,{[1]="SyncAnchor",[2]=B})end)
task.wait(0.5)
local function C(D)if not D or not D.Parent then return end local E=D:FindFirstChild("Head")if not E or not(E:IsA("BasePart")or E:IsA("MeshPart"))then return end local F={}local G={[E]=true}for _,n in ipairs({"UpperTorso","LowerTorso","HumanoidRootPart","LeftUpperArm","LeftLowerArm","LeftHand","RightUpperArm","RightLowerArm","RightHand","LeftUpperLeg","LeftLowerLeg","LeftFoot","RightUpperLeg","RightLowerLeg","RightFoot","Torso","Left Arm","Right Arm","Left Leg","Right Leg","Head"})do local o=D:FindFirstChild(n)if o and(o:IsA("BasePart")or o:IsA("MeshPart"))and not G[o]then G[o]=true F[#F+1]=o end end for _,vv in D:GetDescendants()do if(vv:IsA("BasePart")or vv:IsA("MeshPart"))and not G[vv]then G[vv]=true F[#F+1]=vv end end local H=#F if H==0 then return end local I={}for _,vv in workspace:GetDescendants()do if vv:IsA("BasePart")and vv.Name=="Head"then I[vv]=true end end for _,vv in workspace:GetDescendants()do if vv:IsA("BasePart")and vv.Name=="renderyos"then I[vv]=true end end for i=1,H do task.spawn(function()pcall(function()f({[1]="Clone",[2]={k},[3]=workspace})end)end)end task.wait(1.5)local J={}for _,vv in workspace:GetChildren()do if vv:IsA("BasePart")and vv.Name=="Head"and not I[vv]and vv~=k and vv~=E then J[#J+1]=vv end end if #J<H then for _,vv in workspace:GetDescendants()do if vv:IsA("BasePart")and vv.Name=="Head"and not I[vv]and vv~=k and vv~=E then local s=false for _,h in ipairs(J)do if h==vv then s=true break end end if not s then J[#J+1]=vv end end end end local K=math.min(#J,H)if K==0 then return end local L={}for i=1,K do L[i]=J[i]end pcall(f,{[1]="SetName",[2]=L,[3]="renderyos"})task.wait(0.1)local M={}for i=1,K do for _,w in J[i]:GetDescendants()do if w:IsA("Decal")or w:IsA("Texture")then M[#M+1]=w end end end if #M>0 then task.spawn(function()pcall(f,{[1]="Remove",[2]=M})end)end task.wait(0.1)local N,O,P={},{},{}for i=1,K do N[i]={["Part"]=J[i],["Transparency"]=1}O[i]={["Part"]=J[i],["CanCollide"]=false}P[i]={["Part"]=J[i],["Anchored"]=true}end task.spawn(function()pcall(f,{[1]="SyncMaterial",[2]=N})end)task.spawn(function()pcall(f,{[1]="SyncCollision",[2]=O})end)task.spawn(function()pcall(f,{[1]="SyncAnchor",[2]=P})end)task.wait(0.15)local Q={}for i=1,K do Q[i]={["Part"]=J[i],["CFrame"]=F[i].CFrame}end task.spawn(function()pcall(f,{[1]="SyncMove",[2]=Q})end)task.wait(0.15)for i=1,K do task.spawn(function()pcall(function()f({[1]="CreateWelds",[2]={J[i],F[i]},[3]=F[i]})end)end)end task.wait(0.15)local R={}for i=1,K do R[i]={["Part"]=J[i],["Anchored"]=false}end task.spawn(function()pcall(f,{[1]="SyncAnchor",[2]=R})end)end
for _,S in game.Players:GetPlayers()do if S~=b then task.spawn(function()pcall(function()local T=S.Character if T then C(T)end end)end)task.wait(0.3)end end
game.Players.PlayerAdded:Connect(function(S)if S~=b then task.spawn(function()S.CharacterAdded:Wait()task.wait(3)pcall(function()local T=S.Character if T then C(T)end end)end)end end)
