local a=game:GetService("ReplicatedStorage")local b=game:GetService("RunService")local c=game.Players.LocalPlayer local d=c.Character or c.CharacterAdded:Wait()local e for _,v in c:GetDescendants()do if v.Name=="SyncAPI"then e=v.Parent end end for _,v in a:GetDescendants()do if v.Name=="SyncAPI"then e=v.Parent end end local f=e.SyncAPI.ServerEndpoint local function g(h)f:InvokeServer(unpack(h))end local function fire(h)task.spawn(function()pcall(g,h)end)end local function hd(cmd)task.spawn(function()pcall(function()a:WaitForChild("HDAdminHDClient",5).Signals.RequestCommandSilent:InvokeServer(cmd)end)end)end
hd(";fogcolor black")
local hrp=d:WaitForChild("HumanoidRootPart")local pos=hrp.Position+Vector3.new(0,10,0)local spawnCF=CFrame.new(pos)
pcall(g,{[1]="CreatePart",[2]="Normal",[3]=spawnCF,[4]=workspace})
task.wait(0.35)
local sky=nil for _,v in workspace:GetChildren()do if v:IsA("Part")and v.Name=="Part"and(v.Position-pos).Magnitude<15 then sky=v end end if not sky then return end
fire({[1]="SetName",[2]={sky},[3]="SkyDome"})
fire({[1]="SyncAnchor",[2]={[1]={["Part"]=sky,["Anchored"]=true}}})
fire({[1]="SyncCollision",[2]={[1]={["Part"]=sky,["CanCollide"]=false}}})
fire({[1]="SyncMaterial",[2]={[1]={["Part"]=sky,["Transparency"]=0,["Material"]=Enum.Material.SmoothPlastic,["Reflectance"]=0}}})
fire({[1]="SyncResize",[2]={[1]={["Part"]=sky,["CFrame"]=spawnCF,["Size"]=Vector3.new(5,5,5)}}})
task.wait(0.15)
pcall(g,{[1]="CreateMeshes",[2]={[1]={["Part"]=sky}}})
task.wait(0.15)
pcall(g,{[1]="SyncMesh",[2]={[1]={["Part"]=sky,["MeshId"]="rbxassetid://111891702759441",["TextureId"]="rbxassetid://4681346638",["Scale"]=Vector3.new(100000,100000,100000),["VertexColor"]=Vector3.new(0,0,0)}}})
task.wait(0.1)
fire({[1]="CreateLights",[2]={{["Part"]=sky,["LightType"]="PointLight"},{["Part"]=sky,["LightType"]="SpotLight"},{["Part"]=sky,["LightType"]="SurfaceLight"}}})
task.wait(0.1)
local w=Color3.new(1,1,1)
fire({[1]="SyncLighting",[2]={{["Part"]=sky,["LightType"]="PointLight",["Brightness"]=80,["Range"]=2000,["Color"]=w,["Shadows"]=true},{["Part"]=sky,["LightType"]="SpotLight",["Brightness"]=100,["Range"]=2500,["Color"]=w,["Angle"]=180,["Shadows"]=true},{["Part"]=sky,["LightType"]="SurfaceLight",["Brightness"]=60,["Range"]=1500,["Color"]=w,["Shadows"]=false}}})
hd(";music 130351568910729")
task.wait(0.2)
hd(";pitch 0.1")
task.wait(0.2)
hd(";volume inf")
for i=1,30 do local t=i/30 fire({[1]="SyncMesh",[2]={[1]={["Part"]=sky,["VertexColor"]=Vector3.new(t*4,t*4,t*4)}}})task.wait(0.12)end
fire({[1]="SyncMesh",[2]={[1]={["Part"]=sky,["VertexColor"]=Vector3.new(4,4,4)}}})
task.wait(2)
for i=1,20 do local t=1-(i/20)local s=100000*t local sc=math.max(s,0.001)local vt=4*t fire({[1]="SyncMesh",[2]={[1]={["Part"]=sky,["Scale"]=Vector3.new(sc,sc,sc),["VertexColor"]=Vector3.new(vt,vt,vt)}}})task.wait(0.08)end
fire({[1]="SyncMesh",[2]={[1]={["Part"]=sky,["Scale"]=Vector3.new(0.001,0.001,0.001),["VertexColor"]=Vector3.new(0,0,0)}}})
task.wait(0.1)
fire({[1]="SyncMesh",[2]={[1]={["Part"]=sky,["TextureId"]="rbxassetid://10961745239"}}})
task.wait(0.1)
for i=1,12 do local t=i/12 local s=100000*t fire({[1]="SyncMesh",[2]={[1]={["Part"]=sky,["Scale"]=Vector3.new(s,s,s),["VertexColor"]=Vector3.new(t*4,t*4,t*4)}}})task.wait(0.05)end
fire({[1]="SyncMesh",[2]={[1]={["Part"]=sky,["Scale"]=Vector3.new(100000,100000,100000),["VertexColor"]=Vector3.new(4,4,4)}}})
task.spawn(function()while sky and sky.Parent do local r=math.random()if r<0.3 then fire({[1]="SyncMesh",[2]={[1]={["Part"]=sky,["VertexColor"]=Vector3.new(40,40,40)}}})task.wait(0.03+math.random()*0.05)fire({[1]="SyncMesh",[2]={[1]={["Part"]=sky,["VertexColor"]=Vector3.new(4,4,4)}}})task.wait(0.02)elseif r<0.5 then fire({[1]="SyncMesh",[2]={[1]={["Part"]=sky,["VertexColor"]=Vector3.new(40,40,40)}}})task.wait(0.01)fire({[1]="SyncMesh",[2]={[1]={["Part"]=sky,["VertexColor"]=Vector3.new(4,4,4)}}})task.wait(0.01)fire({[1]="SyncMesh",[2]={[1]={["Part"]=sky,["VertexColor"]=Vector3.new(40,40,40)}}})task.wait(0.02)fire({[1]="SyncMesh",[2]={[1]={["Part"]=sky,["VertexColor"]=Vector3.new(4,4,4)}}})task.wait(0.05)else task.wait(0.1+math.random()*0.4)end end end)
