local a=game:GetService("ReplicatedStorage")local b=game:GetService("RunService")local c=game:GetService("UserInputService")local d=game.Players.LocalPlayer local e=d.Character or d.CharacterAdded:Wait()local f for i,v in d:GetDescendants()do if v.Name=="SyncAPI"then f=v.Parent end end for i,v in a:GetDescendants()do if v.Name=="SyncAPI"then f=v.Parent end end local g=f.SyncAPI.ServerEndpoint local function h(j)g:InvokeServer(unpack(j))end local function fire(j)task.spawn(function()pcall(h,j)end)end
local MESH_ID=1531817922 local TEX_ID=4410646513 local slenders={}local fastMode=false local NORMAL_SPEED=8 local FAST_SPEED=55 local LERP_NORMAL=0.06 local LERP_FAST=0.18 local TELEPORT_CHANCE=0.008 local TELEPORT_RANGE=40 local KILL_RANGE=6 local DETECT_RANGE=120 local MAX_SLENDERS=50 local slenderCount=0 local deadModels={}local HOVER=5
local gui=Instance.new("ScreenGui")gui.Name="SlenderPanel"gui.ResetOnSpawn=false gui.Parent=d.PlayerGui
local frame=Instance.new("Frame")frame.Size=UDim2.new(0,220,0,160)frame.Position=UDim2.new(0,12,1,-172)frame.BackgroundColor3=Color3.fromRGB(18,18,18)frame.BorderSizePixel=1 frame.BorderColor3=Color3.fromRGB(60,60,60)frame.Parent=gui
local title=Instance.new("TextLabel")title.Size=UDim2.new(1,0,0,24)title.Position=UDim2.new(0,0,0,0)title.BackgroundTransparency=1 title.Text="Slenderman Infection"title.TextColor3=Color3.fromRGB(200,200,200)title.TextSize=14 title.Font=Enum.Font.SourceSansBold title.Parent=frame
local line1=Instance.new("TextLabel")line1.Size=UDim2.new(1,-12,0,18)line1.Position=UDim2.new(0,6,0,28)line1.BackgroundTransparency=1 line1.Text="Z - spawn slenderman"line1.TextColor3=Color3.fromRGB(160,160,160)line1.TextSize=13 line1.Font=Enum.Font.SourceSans line1.TextXAlignment=Enum.TextXAlignment.Left line1.Parent=frame
local line2=Instance.new("TextLabel")line2.Size=UDim2.new(1,-12,0,18)line2.Position=UDim2.new(0,6,0,48)line2.BackgroundTransparency=1 line2.Text="Y - toggle fast mode"line2.TextColor3=Color3.fromRGB(160,160,160)line2.TextSize=13 line2.Font=Enum.Font.SourceSans line2.TextXAlignment=Enum.TextXAlignment.Left line2.Parent=frame
local line3=Instance.new("TextLabel")line3.Size=UDim2.new(1,-12,0,18)line3.Position=UDim2.new(0,6,0,68)line3.BackgroundTransparency=1 line3.Text="X - clear all slendermen"line3.TextColor3=Color3.fromRGB(160,160,160)line3.TextSize=13 line3.Font=Enum.Font.SourceSans line3.TextXAlignment=Enum.TextXAlignment.Left line3.Parent=frame
local line4=Instance.new("TextLabel")line4.Size=UDim2.new(1,-12,0,18)line4.Position=UDim2.new(0,6,0,88)line4.BackgroundTransparency=1 line4.Text="kills players, npcs, and humanoid models"line4.TextColor3=Color3.fromRGB(120,120,120)line4.TextSize=11 line4.Font=Enum.Font.SourceSans line4.TextXAlignment=Enum.TextXAlignment.Left line4.Parent=frame
local modeLabel=Instance.new("TextLabel")modeLabel.Size=UDim2.new(1,-12,0,18)modeLabel.Position=UDim2.new(0,6,0,112)modeLabel.BackgroundTransparency=1 modeLabel.Text="mode: normal"modeLabel.TextColor3=Color3.fromRGB(100,180,100)modeLabel.TextSize=13 modeLabel.Font=Enum.Font.SourceSansBold modeLabel.TextXAlignment=Enum.TextXAlignment.Left modeLabel.Parent=frame
local countLabel=Instance.new("TextLabel")countLabel.Size=UDim2.new(1,-12,0,18)countLabel.Position=UDim2.new(0,6,0,132)countLabel.BackgroundTransparency=1 countLabel.Text="active: 0"countLabel.TextColor3=Color3.fromRGB(100,100,100)countLabel.TextSize=12 countLabel.Font=Enum.Font.SourceSans countLabel.TextXAlignment=Enum.TextXAlignment.Left countLabel.Parent=frame
local function getModelPos(model)if not model or not model.Parent then return nil end local r=model:FindFirstChild("HumanoidRootPart")or model:FindFirstChild("Torso")or model:FindFirstChild("UpperTorso")or model:FindFirstChild("Head")or model.PrimaryPart if r and r:IsA("BasePart")and r.Parent then return r.Position end for _,v in model:GetDescendants()do if v:IsA("BasePart")then return v.Position end end return nil end
local function isTargetable(model)if not model or not model.Parent then return false end if deadModels[model]then return false end if model:FindFirstChildOfClass("Humanoid")then local pos=getModelPos(model)if pos then return true end end return false end
local function getTargets()local list={}e=d.Character for _,obj in workspace:GetDescendants()do if obj:IsA("Model")and obj~=e and isTargetable(obj)then list[#list+1]=obj end end return list end
local function findClosest(pos)local best,bestDist=nil,math.huge for _,en in ipairs(getTargets())do local ep=getModelPos(en)if ep then local dist=(ep-pos).Magnitude if dist<bestDist and dist<=DETECT_RANGE then best,bestDist=en,dist end end end return best,bestDist end
local function getGroundY(pos)local params=RaycastParams.new()params.FilterType=Enum.RaycastFilterType.Exclude local filterList={}if e then filterList[#filterList+1]=e end for _,s in ipairs(slenders)do if s and s.Parent then filterList[#filterList+1]=s end end params.FilterDescendantsInstances=filterList local ray=workspace:Raycast(Vector3.new(pos.X,pos.Y+100,pos.Z),Vector3.new(0,-500,0),params)if ray then return ray.Position.Y end return nil end
local function killTarget(model)if not model or not model.Parent or deadModels[model]then return end deadModels[model]=true
	task.spawn(function()local parts={}for _,v in model:GetDescendants()do if v:IsA("BasePart")and v.Parent then parts[#parts+1]=v end end if #parts==0 then return end local cBatch,mBatch={},{}for i,p in ipairs(parts)do cBatch[i]={["Part"]=p,["Color"]=Color3.fromRGB(25,25,25),["UnionColoring"]=false}mBatch[i]={["Part"]=p,["Material"]=Enum.Material.SmoothPlastic,["Transparency"]=0,["Reflectance"]=0}end fire({[1]="SyncColor",[2]=cBatch})fire({[1]="SyncMaterial",[2]=mBatch})end)
	task.spawn(function()local toRm={}for _,v in model:GetChildren()do if v:IsA("Accessory")or v:IsA("Hat")then local hnd=v:FindFirstChild("Handle")if hnd and hnd:IsA("BasePart")then toRm[#toRm+1]=hnd end for _,cc in v:GetDescendants()do if cc:IsA("BasePart")and cc~=hnd then toRm[#toRm+1]=cc end end end end if #toRm>0 then fire({[1]="Remove",[2]=toRm})end end)
	task.spawn(function()task.wait(0.3)local head=model:FindFirstChild("Head")if head and head:IsA("BasePart")then fire({[1]="Remove",[2]={head}})return end local hum=model:FindFirstChildOfClass("Humanoid")if hum then local rootPart=model:FindFirstChild("HumanoidRootPart")or model:FindFirstChild("Torso")or model:FindFirstChild("UpperTorso")if rootPart and rootPart:IsA("BasePart")then fire({[1]="Remove",[2]={rootPart}})return end end local allParts={}for _,v in model:GetDescendants()do if v:IsA("BasePart")then allParts[#allParts+1]=v end end if #allParts>0 then fire({[1]="Remove",[2]=allParts})end end)end
local function clearAll()local toRemove={}for i=#slenders,1,-1 do local s=slenders[i]if s and s.Parent then toRemove[#toRemove+1]=s end table.remove(slenders,i)end if #toRemove>0 then task.spawn(function()pcall(h,{[1]="Remove",[2]=toRemove})end)end slenderCount=0 countLabel.Text="active: 0"end
local function spawnSlender()if slenderCount>=MAX_SLENDERS then return end slenderCount=slenderCount+1 countLabel.Text="active: "..slenderCount e=d.Character or d.CharacterAdded:Wait()local startPos=(e and e:FindFirstChild("HumanoidRootPart")and e.HumanoidRootPart.Position or Vector3.new(0,10,0))+Vector3.new(math.random(-15,15),0,math.random(-15,15))local gy=getGroundY(startPos)local spawnY=gy and(gy+HOVER)or(startPos.Y)local spawnCF=CFrame.new(startPos.X,spawnY,startPos.Z)
	pcall(h,{[1]="CreatePart",[2]="Normal",[3]=spawnCF,[4]=workspace})
	task.wait(0.35)
	local slenderPart=nil for _,v in workspace:GetChildren()do if v:IsA("Part")and v.Name=="Part"and(v.Position-spawnCF.Position).Magnitude<14 then slenderPart=v end end if not slenderPart then slenderCount=math.max(0,slenderCount-1)countLabel.Text="active: "..slenderCount return end
	fire({[1]="SetName",[2]={slenderPart},[3]="Slenderman"})fire({[1]="SyncColor",[2]={[1]={["Part"]=slenderPart,["Color"]=Color3.fromRGB(15,15,15),["UnionColoring"]=false}}})fire({[1]="SyncMaterial",[2]={[1]={["Part"]=slenderPart,["Material"]=Enum.Material.SmoothPlastic,["Transparency"]=0,["Reflectance"]=0}}})fire({[1]="SyncResize",[2]={[1]={["Part"]=slenderPart,["CFrame"]=slenderPart.CFrame,["Size"]=Vector3.new(4,7,2)}}})fire({[1]="SyncAnchor",[2]={[1]={["Part"]=slenderPart,["Anchored"]=true}}})fire({[1]="SyncCollision",[2]={[1]={["Part"]=slenderPart,["CanCollide"]=false}}})
	task.spawn(function()task.wait(0.2)pcall(h,{[1]="CreateMeshes",[2]={[1]={["Part"]=slenderPart}}})task.wait(0.15)fire({[1]="SyncMesh",[2]={[1]={["Part"]=slenderPart,["MeshId"]="rbxassetid://"..MESH_ID}}})task.wait(0.1)fire({[1]="SyncMesh",[2]={[1]={["Part"]=slenderPart,["TextureId"]="rbxassetid://"..TEX_ID}}})task.wait(0.1)fire({[1]="SyncMesh",[2]={[1]={["Part"]=slenderPart,["Scale"]=Vector3.new(1.8,1.8,1.8)}}})end)
	task.spawn(function()local baseX=spawnCF.Position.X local baseZ=spawnCF.Position.Z local baseY=spawnY local smoothX=baseX local smoothZ=baseZ local goalX=baseX local goalZ=baseZ local facingAngle=math.random()*math.pi*2 local wanderAngle=facingAngle local wanderDirX=math.cos(wanderAngle)local wanderDirZ=math.sin(wanderAngle)local wanderTgtX=wanderDirX local wanderTgtZ=wanderDirZ local wanderChangeTime=tick()+math.random(20,50)/10 local lastNetPush=0 local birthTime=tick()local currentTarget=nil local lastTpTime=tick()local lastKillTime=0
		local conn conn=b.Heartbeat:Connect(function(dt)if not slenderPart or not slenderPart.Parent then conn:Disconnect()slenderCount=math.max(0,slenderCount-1)countLabel.Text="active: "..slenderCount return end
			local now=tick()local elapsed=now-birthTime local speed=fastMode and FAST_SPEED or NORMAL_SPEED local lerpA=fastMode and LERP_FAST or LERP_NORMAL local bob=math.sin(elapsed*1.2*math.pi*2)*0.12
			if currentTarget and not isTargetable(currentTarget)then currentTarget=nil end if not currentTarget then currentTarget=findClosest(Vector3.new(smoothX,baseY,smoothZ))end
			if currentTarget and math.floor(now*2)~=math.floor((now-dt)*2)then local closer,cDist=findClosest(Vector3.new(smoothX,baseY,smoothZ))if closer and closer~=currentTarget then local curPos=getModelPos(currentTarget)if curPos then local curDist=(curPos-Vector3.new(smoothX,baseY,smoothZ)).Magnitude if cDist<curDist*0.6 then currentTarget=closer end else currentTarget=closer end end end
			local target=currentTarget local targetPos=target and getModelPos(target)
			if target and targetPos then local dx=targetPos.X-smoothX local dz=targetPos.Z-smoothZ local dist=math.sqrt(dx*dx+dz*dz)
				if math.random()<TELEPORT_CHANCE and(now-lastTpTime)>3 and dist>12 then lastTpTime=now local tpX=targetPos.X+math.random(-6,6)local tpZ=targetPos.Z+math.random(-6,6)local tpGy=getGroundY(Vector3.new(tpX,0,tpZ))if tpGy and tpGy>-50 then smoothX=tpX smoothZ=tpZ baseY=tpGy+HOVER goalX=tpX goalZ=tpZ end end
				if dist<=KILL_RANGE then if now-lastKillTime>0.8 then lastKillTime=now task.spawn(function()killTarget(target)end)currentTarget=nil end goalX=targetPos.X goalZ=targetPos.Z local orbGy=getGroundY(Vector3.new(goalX,0,goalZ))if orbGy and orbGy>-50 then baseY=orbGy+HOVER end else local flatDist=math.max(dist,0.01)local dirX=dx/flatDist local dirZ=dz/flatDist goalX=smoothX+dirX*speed*dt goalZ=smoothZ+dirZ*speed*dt facingAngle=math.atan2(dirZ,dirX)local chaseGy=getGroundY(Vector3.new(goalX,0,goalZ))if chaseGy and chaseGy>-50 then baseY=chaseGy+HOVER elseif not chaseGy then else goalX=smoothX goalZ=smoothZ end end else currentTarget=nil
				if now>=wanderChangeTime then wanderAngle=wanderAngle+(math.random()-0.5)*math.pi*0.5 wanderTgtX=math.cos(wanderAngle)wanderTgtZ=math.sin(wanderAngle)wanderChangeTime=now+math.random(20,45)/10 end wanderDirX=wanderDirX+(wanderTgtX-wanderDirX)*0.02 wanderDirZ=wanderDirZ+(wanderTgtZ-wanderDirZ)*0.02 local wMag=math.sqrt(wanderDirX*wanderDirX+wanderDirZ*wanderDirZ)if wMag>0.01 then wanderDirX=wanderDirX/wMag wanderDirZ=wanderDirZ/wMag end local wanderSpeed=fastMode and FAST_SPEED*0.5 or NORMAL_SPEED*0.4 local nextX=smoothX+wanderDirX*wanderSpeed*dt local nextZ=smoothZ+wanderDirZ*wanderSpeed*dt local wGy=getGroundY(Vector3.new(nextX,0,nextZ))if wGy and wGy>-50 then goalX=nextX goalZ=nextZ baseY=wGy+HOVER facingAngle=math.atan2(wanderDirZ,wanderDirX)elseif not wGy then goalX=nextX goalZ=nextZ facingAngle=math.atan2(wanderDirZ,wanderDirX)else wanderAngle=wanderAngle+math.pi wanderDirX=math.cos(wanderAngle)wanderDirZ=math.sin(wanderAngle)wanderTgtX=wanderDirX wanderTgtZ=wanderDirZ goalX=smoothX goalZ=smoothZ end
				if math.random()<TELEPORT_CHANCE*0.5 and(now-lastTpTime)>5 then lastTpTime=now local tpX=smoothX+math.random(-TELEPORT_RANGE,TELEPORT_RANGE)local tpZ=smoothZ+math.random(-TELEPORT_RANGE,TELEPORT_RANGE)local tpGy=getGroundY(Vector3.new(tpX,0,tpZ))if tpGy and tpGy>-50 then smoothX=tpX smoothZ=tpZ baseY=tpGy+HOVER goalX=tpX goalZ=tpZ elseif not tpGy then smoothX=tpX smoothZ=tpZ goalX=tpX goalZ=tpZ end end end
			smoothX=smoothX+(goalX-smoothX)*lerpA smoothZ=smoothZ+(goalZ-smoothZ)*lerpA local finalY=baseY+bob
			if now-lastNetPush>=1/25 then lastNetPush=now local lookCF=CFrame.new(smoothX,finalY,smoothZ)*CFrame.Angles(0,-facingAngle-math.pi/2,0)fire({[1]="SyncMove",[2]={[1]={["Part"]=slenderPart,["CFrame"]=lookCF}}})end end)end)
	slenders[#slenders+1]=slenderPart end
c.InputBegan:Connect(function(input,gpe)if gpe then return end if input.KeyCode==Enum.KeyCode.Z then task.spawn(spawnSlender)end if input.KeyCode==Enum.KeyCode.Y then fastMode=not fastMode if fastMode then modeLabel.Text="mode: FAST"modeLabel.TextColor3=Color3.fromRGB(220,80,80)else modeLabel.Text="mode: normal"modeLabel.TextColor3=Color3.fromRGB(100,180,100)end end if input.KeyCode==Enum.KeyCode.X then task.spawn(clearAll)end end)
